print("Mahmmed Anish")

dictionaries, set, recursion/problem statements, oop

Fibonacci series using recursion

def fibo(n):
    if(n<=0):
        return -1
    if(n==1):
        return 0
    elif(n==2):
        return 1
    else:
        return fibo(n)+fibo(n-1)
print(fibo(4))

3

sum of fibonacci series

def sumf(val):
    sumn = 1
    return sumn+val

def sumfibo(n):
    if(n<=0):
        return -1
    if(n==1):
        return 0
    elif(n==2):
        return 1
    else:
        val = sumfibo(n-1)+sumfibo(n-2)
        return sumf(val)
print(sumfibo(6))

12

def sumfibo(n):
    if(n<=0):
        return -1
    elif(n==1):
        return 0
    elif(n==2):
        return 1
    else:
        fst = 0
        scnd = 1
        res = fst+scnd
        for i in range(0,n-2):
            next = fst+scnd
            res = fst+scnd
            fst = scnd
            scnd = next
        print(res)
sumfibo(10)

34

map, set, dictionaries

# set is an unordered and unindexed that does not allow dupliates

arr = [1,2,3,4,1,2,5,6,7,3,4]
myset = set(arr)
print(myset)

{1, 2, 3, 4, 5, 6, 7}

myset.add(8)  #it will add an element to the set

print(myset)

{1, 2, 3, 4, 5, 6, 7}

myset.clear()  #it will clear the elements of the set

print(myset)

set()

myset.copy()  #this method will return a copy of a set
print(myset)

set()

# dictionaries
# => key-value, ordered, changeable, not-duplicates

mydict = {
    "name" : "anish",
    "age" : 24,
    "occupation" : "student"
}
print(mydict)

{'name': 'anish', 'age': 24, 'occupation': 'student'}

print(type(mydict))

<class 'dict'>

print(mydict("name"))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [19], in <cell line: 1>()
----> 1 print(mydict("name"))

TypeError: 'dict' object is not callable

